apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tmf-product-catalog-management-api
  labels:
    app.kubernetes.io/part-of: tmf-product-catalog-management-api
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    vodafone.com/check-api-conformance: "true"
spec:
  source:
    git:
      url: https://github.com/tsalm-pivotal/tm-forum-js.git
      ref:
        branch: main
